### ISSUE TITLE
运行脚本是提示错误

### ISSUE THREAD

**Issue by avinrock** [OreosLab/bili#64]
## 开始执行... 2022-12-29 08:40:30

当前版本:
最新版本:2.1.3
已经是最新版本，不需要更新！！！
配置文件路径:/ql/config/java_conf.json
2022-12-29 08:40:33.302 ERROR t.m.u.HttpUtils - java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Exception in thread "main" java.lang.NullPointerException
	at top.misec.utils.HttpUtils.closeResource(HttpUtils.java:173)
	at top.misec.utils.HttpUtils.doGet(HttpUtils.java:131)
	at top.misec.utils.HttpUtils.doGet(HttpUtils.java:138)
	at top.misec.utils.HttpUtils.doGet(HttpUtils.java:106)
	at top.misec.utils.VersionInfo.printVersionInfo(VersionInfo.java:32)
	at top.misec.BiliMain.main(BiliMain.java:26)

## 执行结束... 2022-12-29 08:40:33 耗时 3 秒

**Comment by skyunix** [comment]
要翻墙
